# -*- mode: ruby -*-
# vi: set ft=ruby :

#=========#
# Airflow #
#=========#
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"

  config.vm.define "airflow" do |airflow|
    airflow.vm.hostname = "airflow"
    airflow.vm.provider "virtualbox" do |vb|    
      vb.name = "airflow"
      vb.cpus = 4
      vb.memory = "4096"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update && apt upgrade -y && apt autoremove -y
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    systemctl restart ssh
  SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt install python3-pip -y
    AIRFLOW_VERSION=2.2.5
    PYTHON_VERSION="$(python3 --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
    CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
    pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
    echo -e "\nexport PATH=$PATH:~/.local/bin\n" >>/home/vagrant/.bashrc
    curl -s https://raw.githubusercontent.com/ehsqjfwk99999/config-files/main/.bashrc >>/home/vagrant/.bashrc
    curl -s https://raw.githubusercontent.com/ehsqjfwk99999/config-files/main/.vimrc >>/home/vagrant/.vimrc
  SHELL
      
end
